version: '3.3'

services:
 

  mailcow-proxy:
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      # - traefik.http.routers.nextcloud_insecure.entrypoints=web
      # - traefik.http.routers.nextcloud_insecure.rule=Host(`${HOST}`)

      - traefik.http.routers.mailcow-proxy.entrypoints=websecure
      - traefik.http.routers.mailcow-proxy.rule=Host(`${HOST}`)
      - traefik.http.routers.mailcow-proxy.tls=true
      # - traefik.http.routers.mailcow-proxy.tls.certresolver=letsencrypt


   
networks:
  traefik-proxy:
    external: true
