version: '3.3'

services:
  db-nextcloud:
    image: mariadb:latest   
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}

    networks:
      - nextcloud-network

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    # ports:
    #   - "8000:80"
    #   - "8443:443"
    links:
      - db-nextcloud
    networks:
      - nextcloud-network
      - traefik-proxy
    volumes:
      - nextcloud-app:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db-nextcloud
      - TRUSTED_PROXIES=172.70.255.159
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOST}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      # - traefik.http.routers.nextcloud_insecure.entrypoints=web
      # - traefik.http.routers.nextcloud_insecure.rule=Host(`${HOST}`)

      - traefik.http.routers.nexcloud.entrypoints=websecure
      - traefik.http.routers.nexcloud.rule=Host(`${HOST}`)
      - traefik.http.routers.nexcloud.tls=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirectregex
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement='https://$${1}/remote.php/dav'
      # - traefik.http.routers.nexcloud.tls.certresolver=letsencrypt


   
networks:
  nextcloud-network:
    external: true
  traefik-proxy:
    external: true
volumes:
 nextcloud-app:
 nextcloud-db:
