version: '3.3'

services:
  db-nextcloud:
    image: mariadb:latest   
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-network

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - db-nextcloud
    networks:
      - nextcloud-network
      - traefik-proxy
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.nexcloud_insecure.entrypoints=web
      - traefik.http.routers.nexcloud_insecure.rule=Host(`nextcloud.localhost`)
      # - traefik.http.routers.nexcloud_insecure.middlewares=redirect@file

      # - traefik.http.routers.gitlab.entrypoints=web-secure
      # - traefik.http.routers.gitlab.rule=Host(`gitlab.domain.com`)
      # - traefik.http.routers.gitlab.tls.certresolver=letsencrypt
      # - traefik.http.services.gitlab.loadbalancer.server.port=80


      # Can't filter TCP traffic on SNI, see link below
      # https://community.containo.us/t/routing-ssh-traffic-with-traefik-v2/717/6
      # - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      # - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      # - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      # - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=22
networks:
  nextcloud-network:
    external: true
  traefik-proxy:
    external: true
volumes:
  nextcloud:
  db-nextcloud: