version: '3.3'

services:
  db-nextcloud:
    image: mariadb:latest   
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}

    networks:
      - nextcloud-network

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - db-nextcloud
    networks:
      - nextcloud-network
      - traefik-proxy
    volumes:
      - nextcloud-app:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db-nextcloud
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.nextcloud_insecure.entrypoints=web
      - traefik.http.routers.nextcloud_insecure.rule=Host(`${HOST}`)

      - traefik.http.routers.nexcloud.entrypoints=websecure
      - traefik.http.routers.nexcloud.rule=Host(`${HOST}`)
      # - traefik.http.routers.nexcloud.tls.certresolver=letsencrypt


      # Can't filter TCP traffic on SNI, see link below
      # https://community.containo.us/t/routing-ssh-traffic-with-traefik-v2/717/6
      # - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      # - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      # - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      # - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=22
networks:
  nextcloud-network:
    external: true
  traefik-proxy:
    external: true
volumes:
 nextcloud-app:
 nextcloud-db:
